openapi: 3.0.3
info:
  title: Rate Api
  description: Handle the info about rates in platform
  version: "1.0"
tags:
- name: rates
  description: Available operations for rates domain.
paths:
  /v1/rate:
    post:
      tags:
      - rate
      summary: Create a new rate
      operationId: addRate
      requestBody:
        description: Use the required fields to create a new rate.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rate'
        required: true
      responses:
        201:
          description: Use the required fields to create a new rate.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rate'
        422:
          description: Invalid price or currency code format
          content: {}
        503:
          description: Service unavailable
          content: {}
components:
  schemas:
    Rate:
      type: object
      properties:
        id:
          type: string
          example: "1234"
        brandId:
          type: string
          description: Unique brand identifier
          example: "1234"
        productId:
          type: string
          description: Unique product identifier
          example: "1234"
        startDate:
          type: string
          description: Rate service start date in YYYY-mm-dd format
          format: date
          example: "2021-05-24"
        endDate:
          type: string
          description: Rate service end date in YYYY-mm-dd format
          format: date
          example: "2021-12-24"
        price:
          type: integer
          description: Product price without decimals
          example: 324
        currencyCode:
          type: string
          description: ID of the currency in which the price is represented
          example: EUR
      required:
      - id
      - brandId
      - productId
      - startDate
      - price
      - currencyCode