version: '3.3'
services:
  rate-wiremock:
    image: wiremock/wiremock:latest
    ports:
    - '7070:8080'
    - '7443:8443'
    volumes:
    - ./wiremock/__files:/home/wiremock/__files
    - ./wiremock/mappings:/home/wiremock/mappings

  cacheRedis:
    container_name: redis
    image: redis
    ports:
    - '6379:6379'

  dbRates:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rateservicedb
    ports:
    - "5432:5432"
    volumes:
    - ./postgreSQL/init-db.sql:/docker-entrypoint-initdb.d/init.sql